# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_surveying.ui'
#
# Created: Thu Jun 13 01:29:30 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(771, 497)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("")
        self.maprenderer = QtGui.QTabWidget(Form)
        self.maprenderer.setGeometry(QtCore.QRect(0, 0, 770, 500))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maprenderer.sizePolicy().hasHeightForWidth())
        self.maprenderer.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(166, 166, 166))
        gradient.setColorAt(0.08, QtGui.QColor(127, 127, 127))
        gradient.setColorAt(0.9, QtGui.QColor(76, 76, 76))
        gradient.setColorAt(1.0, QtGui.QColor(51, 51, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.maprenderer.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.maprenderer.setFont(font)
        self.maprenderer.setMouseTracking(False)
        self.maprenderer.setFocusPolicy(QtCore.Qt.TabFocus)
        self.maprenderer.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.maprenderer.setAcceptDrops(True)
        self.maprenderer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.maprenderer.setAutoFillBackground(False)
        self.maprenderer.setStyleSheet("QTabWidget {\n"
"border: none;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #a6a6a6, stop: 0.08 #7f7f7f,\n"
"\n"
"stop: 0.9 #4c4c4c, stop: 1 #333333);\n"
"}")
        self.maprenderer.setTabShape(QtGui.QTabWidget.Rounded)
        self.maprenderer.setElideMode(QtCore.Qt.ElideNone)
        self.maprenderer.setDocumentMode(False)
        self.maprenderer.setTabsClosable(False)
        self.maprenderer.setMovable(False)
        self.maprenderer.setObjectName("maprenderer")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 760, 480))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_28 = QtGui.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(90, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtGui.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(190, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtGui.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(20, 70, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtGui.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(20, 200, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtGui.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(20, 110, 21, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtGui.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(10, 140, 31, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.hesapla_to1 = QtGui.QPushButton(self.tab_5)
        self.hesapla_to1.setGeometry(QtCore.QRect(30, 10, 61, 26))
        self.hesapla_to1.setObjectName("hesapla_to1")
        self.sil_to1 = QtGui.QPushButton(self.tab_5)
        self.sil_to1.setGeometry(QtCore.QRect(110, 10, 31, 26))
        self.sil_to1.setObjectName("sil_to1")
        self.Ya_to1 = QtGui.QLineEdit(self.tab_5)
        self.Ya_to1.setGeometry(QtCore.QRect(40, 70, 101, 20))
        self.Ya_to1.setObjectName("Ya_to1")
        self.Xa_to1 = QtGui.QLineEdit(self.tab_5)
        self.Xa_to1.setGeometry(QtCore.QRect(150, 70, 101, 20))
        self.Xa_to1.setObjectName("Xa_to1")
        self.AB_to1 = QtGui.QLineEdit(self.tab_5)
        self.AB_to1.setGeometry(QtCore.QRect(50, 110, 181, 23))
        self.AB_to1.setObjectName("AB_to1")
        self.ABg_to1 = QtGui.QLineEdit(self.tab_5)
        self.ABg_to1.setGeometry(QtCore.QRect(50, 140, 181, 23))
        self.ABg_to1.setObjectName("ABg_to1")
        self.Yb_to1 = QtGui.QLabel(self.tab_5)
        self.Yb_to1.setGeometry(QtCore.QRect(50, 200, 121, 16))
        self.Yb_to1.setText("")
        self.Yb_to1.setObjectName("Yb_to1")
        self.Xb_to1 = QtGui.QLabel(self.tab_5)
        self.Xb_to1.setGeometry(QtCore.QRect(190, 200, 121, 16))
        self.Xb_to1.setText("")
        self.Xb_to1.setObjectName("Xb_to1")
        self.label_34 = QtGui.QLabel(self.tab_5)
        self.label_34.setGeometry(QtCore.QRect(100, 170, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtGui.QLabel(self.tab_5)
        self.label_35.setGeometry(QtCore.QRect(240, 170, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_42 = QtGui.QLabel(self.tab_5)
        self.label_42.setGeometry(QtCore.QRect(320, 60, 401, 381))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("1.to.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.Ya_to2 = QtGui.QLineEdit(self.tab_6)
        self.Ya_to2.setGeometry(QtCore.QRect(40, 70, 101, 20))
        self.Ya_to2.setObjectName("Ya_to2")
        self.label_51 = QtGui.QLabel(self.tab_6)
        self.label_51.setGeometry(QtCore.QRect(20, 100, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_56 = QtGui.QLabel(self.tab_6)
        self.label_56.setGeometry(QtCore.QRect(20, 70, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.Xa_to2 = QtGui.QLineEdit(self.tab_6)
        self.Xa_to2.setGeometry(QtCore.QRect(150, 70, 101, 20))
        self.Xa_to2.setObjectName("Xa_to2")
        self.label_57 = QtGui.QLabel(self.tab_6)
        self.label_57.setGeometry(QtCore.QRect(190, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.sil_to2 = QtGui.QPushButton(self.tab_6)
        self.sil_to2.setGeometry(QtCore.QRect(110, 10, 31, 26))
        self.sil_to2.setObjectName("sil_to2")
        self.label_58 = QtGui.QLabel(self.tab_6)
        self.label_58.setGeometry(QtCore.QRect(90, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.AB_to2 = QtGui.QLabel(self.tab_6)
        self.AB_to2.setGeometry(QtCore.QRect(70, 150, 151, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.AB_to2.setFont(font)
        self.AB_to2.setText("")
        self.AB_to2.setObjectName("AB_to2")
        self.hesapla_to2 = QtGui.QPushButton(self.tab_6)
        self.hesapla_to2.setGeometry(QtCore.QRect(30, 10, 61, 26))
        self.hesapla_to2.setObjectName("hesapla_to2")
        self.Xb_to2 = QtGui.QLineEdit(self.tab_6)
        self.Xb_to2.setGeometry(QtCore.QRect(150, 100, 101, 20))
        self.Xb_to2.setObjectName("Xb_to2")
        self.ABg_to2 = QtGui.QLabel(self.tab_6)
        self.ABg_to2.setGeometry(QtCore.QRect(70, 180, 141, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.ABg_to2.setFont(font)
        self.ABg_to2.setText("")
        self.ABg_to2.setObjectName("ABg_to2")
        self.Yb_to2 = QtGui.QLineEdit(self.tab_6)
        self.Yb_to2.setGeometry(QtCore.QRect(40, 100, 101, 20))
        self.Yb_to2.setObjectName("Yb_to2")
        self.label_61 = QtGui.QLabel(self.tab_6)
        self.label_61.setGeometry(QtCore.QRect(20, 150, 21, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtGui.QLabel(self.tab_6)
        self.label_62.setGeometry(QtCore.QRect(20, 180, 31, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_37 = QtGui.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(320, 60, 401, 381))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("1.to.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.hesapla_to3 = QtGui.QPushButton(self.tab_7)
        self.hesapla_to3.setGeometry(QtCore.QRect(30, 10, 61, 26))
        self.hesapla_to3.setObjectName("hesapla_to3")
        self.label_41 = QtGui.QLabel(self.tab_7)
        self.label_41.setGeometry(QtCore.QRect(20, 70, 31, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.ABg_to3 = QtGui.QLineEdit(self.tab_7)
        self.ABg_to3.setGeometry(QtCore.QRect(60, 70, 101, 20))
        self.ABg_to3.setObjectName("ABg_to3")
        self.label_40 = QtGui.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(30, 100, 16, 21))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.BCg_to3 = QtGui.QLabel(self.tab_7)
        self.BCg_to3.setGeometry(QtCore.QRect(60, 130, 121, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.BCg_to3.setFont(font)
        self.BCg_to3.setText("")
        self.BCg_to3.setObjectName("BCg_to3")
        self.sil_to3 = QtGui.QPushButton(self.tab_7)
        self.sil_to3.setGeometry(QtCore.QRect(110, 10, 31, 26))
        self.sil_to3.setObjectName("sil_to3")
        self.beta_to3 = QtGui.QLineEdit(self.tab_7)
        self.beta_to3.setGeometry(QtCore.QRect(60, 100, 101, 20))
        self.beta_to3.setObjectName("beta_to3")
        self.label_44 = QtGui.QLabel(self.tab_7)
        self.label_44.setGeometry(QtCore.QRect(20, 130, 31, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_38 = QtGui.QLabel(self.tab_7)
        self.label_38.setGeometry(QtCore.QRect(220, 30, 491, 381))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("3.to.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.Xa_to4 = QtGui.QLineEdit(self.tab_8)
        self.Xa_to4.setGeometry(QtCore.QRect(150, 70, 101, 20))
        self.Xa_to4.setObjectName("Xa_to4")
        self.hesapla_to4 = QtGui.QPushButton(self.tab_8)
        self.hesapla_to4.setGeometry(QtCore.QRect(30, 10, 61, 26))
        self.hesapla_to4.setObjectName("hesapla_to4")
        self.label_48 = QtGui.QLabel(self.tab_8)
        self.label_48.setGeometry(QtCore.QRect(90, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtGui.QLabel(self.tab_8)
        self.label_49.setGeometry(QtCore.QRect(190, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_52 = QtGui.QLabel(self.tab_8)
        self.label_52.setGeometry(QtCore.QRect(20, 70, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtGui.QLabel(self.tab_8)
        self.label_53.setGeometry(QtCore.QRect(20, 180, 41, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.Ya_to4 = QtGui.QLineEdit(self.tab_8)
        self.Ya_to4.setGeometry(QtCore.QRect(40, 70, 101, 20))
        self.Ya_to4.setObjectName("Ya_to4")
        self.label_54 = QtGui.QLabel(self.tab_8)
        self.label_54.setGeometry(QtCore.QRect(20, 100, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.Xb_to4 = QtGui.QLineEdit(self.tab_8)
        self.Xb_to4.setGeometry(QtCore.QRect(150, 100, 101, 20))
        self.Xb_to4.setObjectName("Xb_to4")
        self.ABC_to4 = QtGui.QLabel(self.tab_8)
        self.ABC_to4.setGeometry(QtCore.QRect(70, 180, 101, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.ABC_to4.setFont(font)
        self.ABC_to4.setText("")
        self.ABC_to4.setObjectName("ABC_to4")
        self.sil_to4 = QtGui.QPushButton(self.tab_8)
        self.sil_to4.setGeometry(QtCore.QRect(110, 10, 31, 26))
        self.sil_to4.setObjectName("sil_to4")
        self.Yb_to4 = QtGui.QLineEdit(self.tab_8)
        self.Yb_to4.setGeometry(QtCore.QRect(40, 100, 101, 20))
        self.Yb_to4.setObjectName("Yb_to4")
        self.Xc_to4 = QtGui.QLineEdit(self.tab_8)
        self.Xc_to4.setGeometry(QtCore.QRect(150, 130, 101, 20))
        self.Xc_to4.setObjectName("Xc_to4")
        self.label_63 = QtGui.QLabel(self.tab_8)
        self.label_63.setGeometry(QtCore.QRect(20, 130, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.Yc_to4 = QtGui.QLineEdit(self.tab_8)
        self.Yc_to4.setGeometry(QtCore.QRect(40, 130, 101, 20))
        self.Yc_to4.setObjectName("Yc_to4")
        self.label_64 = QtGui.QLabel(self.tab_8)
        self.label_64.setGeometry(QtCore.QRect(35, 170, 21, 20))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_39 = QtGui.QLabel(self.tab_8)
        self.label_39.setGeometry(QtCore.QRect(310, 20, 491, 381))
        self.label_39.setText("")
        self.label_39.setTextFormat(QtCore.Qt.AutoText)
        self.label_39.setPixmap(QtGui.QPixmap("4.to.png"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.maprenderer.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_onden = QtGui.QFrame(self.tab_4)
        self.frame_onden.setGeometry(QtCore.QRect(10, 40, 703, 412))
        self.frame_onden.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_onden.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_onden.setObjectName("frame_onden")
        self.label_19 = QtGui.QLabel(self.frame_onden)
        self.label_19.setGeometry(QtCore.QRect(190, 20, 481, 381))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("onden.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.a_2 = QtGui.QLineEdit(self.frame_onden)
        self.a_2.setGeometry(QtCore.QRect(31, 10, 129, 25))
        self.a_2.setObjectName("a_2")
        self.y1_2 = QtGui.QLineEdit(self.frame_onden)
        self.y1_2.setGeometry(QtCore.QRect(31, 103, 129, 25))
        self.y1_2.setObjectName("y1_2")
        self.b_2 = QtGui.QLineEdit(self.frame_onden)
        self.b_2.setGeometry(QtCore.QRect(31, 41, 129, 25))
        self.b_2.setObjectName("b_2")
        self.x1_2 = QtGui.QLineEdit(self.frame_onden)
        self.x1_2.setGeometry(QtCore.QRect(31, 72, 129, 25))
        self.x1_2.setObjectName("x1_2")
        self.x2_2 = QtGui.QLineEdit(self.frame_onden)
        self.x2_2.setGeometry(QtCore.QRect(31, 134, 129, 25))
        self.x2_2.setObjectName("x2_2")
        self.y2_2 = QtGui.QLineEdit(self.frame_onden)
        self.y2_2.setGeometry(QtCore.QRect(31, 165, 129, 25))
        self.y2_2.setObjectName("y2_2")
        self.yp_2 = QtGui.QLabel(self.frame_onden)
        self.yp_2.setGeometry(QtCore.QRect(40, 229, 141, 21))
        self.yp_2.setText("")
        self.yp_2.setObjectName("yp_2")
        self.xp_2 = QtGui.QLabel(self.frame_onden)
        self.xp_2.setGeometry(QtCore.QRect(40, 256, 141, 21))
        self.xp_2.setText("")
        self.xp_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.xp_2.setObjectName("xp_2")
        self.label_20 = QtGui.QLabel(self.frame_onden)
        self.label_20.setGeometry(QtCore.QRect(10, 79, 18, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.frame_onden)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 16, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.frame_onden)
        self.label_22.setGeometry(QtCore.QRect(10, 109, 17, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.frame_onden)
        self.label_23.setGeometry(QtCore.QRect(10, 49, 16, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.frame_onden)
        self.label_24.setGeometry(QtCore.QRect(10, 139, 18, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.frame_onden)
        self.label_25.setGeometry(QtCore.QRect(10, 169, 17, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.frame_onden)
        self.label_26.setGeometry(QtCore.QRect(11, 229, 18, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.frame_onden)
        self.label_27.setGeometry(QtCore.QRect(11, 259, 19, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.hesapla_2 = QtGui.QPushButton(self.tab_4)
        self.hesapla_2.setGeometry(QtCore.QRect(10, 10, 94, 26))
        self.hesapla_2.setObjectName("hesapla_2")
        self.temizle_2 = QtGui.QPushButton(self.tab_4)
        self.temizle_2.setGeometry(QtCore.QRect(110, 10, 94, 26))
        self.temizle_2.setObjectName("temizle_2")
        self.maprenderer.addTab(self.tab_4, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_geriden = QtGui.QFrame(self.tab_3)
        self.frame_geriden.setGeometry(QtCore.QRect(10, 40, 749, 412))
        self.frame_geriden.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_geriden.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_geriden.setObjectName("frame_geriden")
        self.label_11 = QtGui.QLabel(self.frame_geriden)
        self.label_11.setGeometry(QtCore.QRect(200, 20, 471, 371))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("geri.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_8 = QtGui.QLabel(self.frame_geriden)
        self.label_8.setGeometry(QtCore.QRect(10, 77, 18, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.frame_geriden)
        self.label_9.setGeometry(QtCore.QRect(10, 14, 16, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.frame_geriden)
        self.label_10.setGeometry(QtCore.QRect(10, 109, 17, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtGui.QLabel(self.frame_geriden)
        self.label_12.setGeometry(QtCore.QRect(10, 46, 16, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.frame_geriden)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 18, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.frame_geriden)
        self.label_14.setGeometry(QtCore.QRect(10, 172, 17, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.frame_geriden)
        self.label_15.setGeometry(QtCore.QRect(10, 203, 18, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.frame_geriden)
        self.label_16.setGeometry(QtCore.QRect(10, 235, 17, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.frame_geriden)
        self.label_17.setGeometry(QtCore.QRect(10, 266, 18, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.frame_geriden)
        self.label_18.setGeometry(QtCore.QRect(10, 298, 19, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.a = QtGui.QLineEdit(self.frame_geriden)
        self.a.setGeometry(QtCore.QRect(31, 14, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.a.setFont(font)
        self.a.setObjectName("a")
        self.y1 = QtGui.QLineEdit(self.frame_geriden)
        self.y1.setGeometry(QtCore.QRect(31, 107, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.y1.setFont(font)
        self.y1.setObjectName("y1")
        self.b = QtGui.QLineEdit(self.frame_geriden)
        self.b.setGeometry(QtCore.QRect(31, 45, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.b.setFont(font)
        self.b.setObjectName("b")
        self.x1 = QtGui.QLineEdit(self.frame_geriden)
        self.x1.setGeometry(QtCore.QRect(31, 76, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.x1.setFont(font)
        self.x1.setObjectName("x1")
        self.x2 = QtGui.QLineEdit(self.frame_geriden)
        self.x2.setGeometry(QtCore.QRect(31, 138, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.x2.setFont(font)
        self.x2.setObjectName("x2")
        self.y2 = QtGui.QLineEdit(self.frame_geriden)
        self.y2.setGeometry(QtCore.QRect(31, 169, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.y2.setFont(font)
        self.y2.setObjectName("y2")
        self.x3 = QtGui.QLineEdit(self.frame_geriden)
        self.x3.setGeometry(QtCore.QRect(31, 200, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.x3.setFont(font)
        self.x3.setObjectName("x3")
        self.y3 = QtGui.QLineEdit(self.frame_geriden)
        self.y3.setGeometry(QtCore.QRect(31, 231, 129, 25))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setUnderline(True)
        self.y3.setFont(font)
        self.y3.setObjectName("y3")
        self.yp = QtGui.QLabel(self.frame_geriden)
        self.yp.setGeometry(QtCore.QRect(31, 262, 121, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.yp.setFont(font)
        self.yp.setText("")
        self.yp.setObjectName("yp")
        self.xp = QtGui.QLabel(self.frame_geriden)
        self.xp.setGeometry(QtCore.QRect(31, 296, 121, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.xp.setFont(font)
        self.xp.setText("")
        self.xp.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.xp.setObjectName("xp")
        self.c = QtGui.QPushButton(self.tab_3)
        self.c.setGeometry(QtCore.QRect(110, 10, 94, 25))
        self.c.setObjectName("c")
        self.hesapla = QtGui.QPushButton(self.tab_3)
        self.hesapla.setGeometry(QtCore.QRect(10, 10, 94, 25))
        self.hesapla.setObjectName("hesapla")
        self.maprenderer.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.hesaplak = QtGui.QPushButton(self.tab_2)
        self.hesaplak.setGeometry(QtCore.QRect(10, 10, 94, 26))
        self.hesaplak.setObjectName("hesaplak")
        self.temizlek = QtGui.QPushButton(self.tab_2)
        self.temizlek.setGeometry(QtCore.QRect(110, 10, 94, 26))
        self.temizlek.setObjectName("temizlek")
        self.frame_karayolu = QtGui.QFrame(self.tab_2)
        self.frame_karayolu.setGeometry(QtCore.QRect(10, 40, 749, 412))
        self.frame_karayolu.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_karayolu.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_karayolu.setObjectName("frame_karayolu")
        self.label_4 = QtGui.QLabel(self.frame_karayolu)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 21, 20))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtGui.QLabel(self.frame_karayolu)
        self.label_7.setGeometry(QtCore.QRect(0, 70, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Tt = QtGui.QLineEdit(self.frame_karayolu)
        self.Tt.setGeometry(QtCore.QRect(30, 90, 113, 27))
        self.Tt.setObjectName("Tt")
        self.BSt = QtGui.QLineEdit(self.frame_karayolu)
        self.BSt.setGeometry(QtCore.QRect(30, 170, 113, 27))
        self.BSt.setObjectName("BSt")
        self.label_2 = QtGui.QLabel(self.frame_karayolu)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 21, 20))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtGui.QLabel(self.frame_karayolu)
        self.label_5.setGeometry(QtCore.QRect(5, 170, 21, 20))
        self.label_5.setObjectName("label_5")
        self.Rt = QtGui.QLineEdit(self.frame_karayolu)
        self.Rt.setGeometry(QtCore.QRect(30, 40, 113, 27))
        self.Rt.setObjectName("Rt")
        self.label = QtGui.QLabel(self.frame_karayolu)
        self.label.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.label.setObjectName("label")
        self.label_3 = QtGui.QLabel(self.frame_karayolu)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 21, 20))
        self.label_3.setObjectName("label_3")
        self.at = QtGui.QLineEdit(self.frame_karayolu)
        self.at.setGeometry(QtCore.QRect(30, 10, 113, 27))
        self.at.setObjectName("at")
        self.Lt = QtGui.QLineEdit(self.frame_karayolu)
        self.Lt.setGeometry(QtCore.QRect(30, 130, 113, 27))
        self.Lt.setObjectName("Lt")
        self.label_6 = QtGui.QLabel(self.frame_karayolu)
        self.label_6.setGeometry(QtCore.QRect(190, 10, 521, 391))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("karayolu.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.maprenderer.addTab(self.tab_2, "")
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.render = QtGui.QPushButton(self.tab_9)
        self.render.setGeometry(QtCore.QRect(230, 60, 281, 71))
        self.render.setObjectName("render")
        self.label_36 = QtGui.QLabel(self.tab_9)
        self.label_36.setGeometry(QtCore.QRect(40, 230, 591, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_36.setTextFormat(QtCore.Qt.RichText)
        self.label_36.setScaledContents(False)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.maprenderer.addTab(self.tab_9, "")
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.raporla = QtGui.QPushButton(self.tab_10)
        self.raporla.setGeometry(QtCore.QRect(230, 60, 281, 71))
        self.raporla.setObjectName("raporla")
        self.label_43 = QtGui.QLabel(self.tab_10)
        self.label_43.setGeometry(QtCore.QRect(40, 230, 591, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_43.setTextFormat(QtCore.Qt.RichText)
        self.label_43.setScaledContents(False)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.maprenderer.addTab(self.tab_10, "")
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_45 = QtGui.QLabel(self.tab_11)
        self.label_45.setGeometry(QtCore.QRect(10, 30, 731, 231))
        self.label_45.setAcceptDrops(False)
        self.label_45.setAutoFillBackground(False)
        self.label_45.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_45.setTextFormat(QtCore.Qt.RichText)
        self.label_45.setScaledContents(False)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_45.setWordWrap(True)
        self.label_45.setOpenExternalLinks(False)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtGui.QLabel(self.tab_11)
        self.label_46.setGeometry(QtCore.QRect(210, 20, 61, 51))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("iconn.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.maprenderer.addTab(self.tab_11, "")

        self.retranslateUi(Form)
        self.maprenderer.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget_2, self.hesapla_to1)
        Form.setTabOrder(self.hesapla_to1, self.sil_to1)
        Form.setTabOrder(self.sil_to1, self.Ya_to1)
        Form.setTabOrder(self.Ya_to1, self.Xa_to1)
        Form.setTabOrder(self.Xa_to1, self.AB_to1)
        Form.setTabOrder(self.AB_to1, self.ABg_to1)
        Form.setTabOrder(self.ABg_to1, self.hesapla_to2)
        Form.setTabOrder(self.hesapla_to2, self.sil_to2)
        Form.setTabOrder(self.sil_to2, self.Ya_to2)
        Form.setTabOrder(self.Ya_to2, self.Xa_to2)
        Form.setTabOrder(self.Xa_to2, self.Yb_to2)
        Form.setTabOrder(self.Yb_to2, self.Xb_to2)
        Form.setTabOrder(self.Xb_to2, self.hesapla_to3)
        Form.setTabOrder(self.hesapla_to3, self.sil_to3)
        Form.setTabOrder(self.sil_to3, self.ABg_to3)
        Form.setTabOrder(self.ABg_to3, self.beta_to3)
        Form.setTabOrder(self.beta_to3, self.hesapla_to4)
        Form.setTabOrder(self.hesapla_to4, self.sil_to4)
        Form.setTabOrder(self.sil_to4, self.Ya_to4)
        Form.setTabOrder(self.Ya_to4, self.Xa_to4)
        Form.setTabOrder(self.Xa_to4, self.Yb_to4)
        Form.setTabOrder(self.Yb_to4, self.Xb_to4)
        Form.setTabOrder(self.Xb_to4, self.Yc_to4)
        Form.setTabOrder(self.Yc_to4, self.Xc_to4)
        Form.setTabOrder(self.Xc_to4, self.hesapla_2)
        Form.setTabOrder(self.hesapla_2, self.temizle_2)
        Form.setTabOrder(self.temizle_2, self.a_2)
        Form.setTabOrder(self.a_2, self.b_2)
        Form.setTabOrder(self.b_2, self.x1_2)
        Form.setTabOrder(self.x1_2, self.y1_2)
        Form.setTabOrder(self.y1_2, self.x2_2)
        Form.setTabOrder(self.x2_2, self.y2_2)
        Form.setTabOrder(self.y2_2, self.hesapla)
        Form.setTabOrder(self.hesapla, self.c)
        Form.setTabOrder(self.c, self.a)
        Form.setTabOrder(self.a, self.b)
        Form.setTabOrder(self.b, self.x1)
        Form.setTabOrder(self.x1, self.y1)
        Form.setTabOrder(self.y1, self.x2)
        Form.setTabOrder(self.x2, self.y2)
        Form.setTabOrder(self.y2, self.x3)
        Form.setTabOrder(self.x3, self.y3)
        Form.setTabOrder(self.y3, self.hesaplak)
        Form.setTabOrder(self.hesaplak, self.temizlek)
        Form.setTabOrder(self.temizlek, self.at)
        Form.setTabOrder(self.at, self.Rt)
        Form.setTabOrder(self.Rt, self.Tt)
        Form.setTabOrder(self.Tt, self.Lt)
        Form.setTabOrder(self.Lt, self.BSt)
        Form.setTabOrder(self.BSt, self.maprenderer)
        Form.setTabOrder(self.maprenderer, self.render)
        Form.setTabOrder(self.render, self.raporla)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "GeoCalculator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Form", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Form", "AB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Form", "(AB)", None, QtGui.QApplication.UnicodeUTF8))
        self.hesapla_to1.setText(QtGui.QApplication.translate("Form", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.sil_to1.setText(QtGui.QApplication.translate("Form", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "1. Temel Ödev", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("Form", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("Form", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.sil_to2.setText(QtGui.QApplication.translate("Form", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.hesapla_to2.setText(QtGui.QApplication.translate("Form", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("Form", "AB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("Form", "(AB)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("Form", "2. Temel Ödev", None, QtGui.QApplication.UnicodeUTF8))
        self.hesapla_to3.setText(QtGui.QApplication.translate("Form", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Form", "(AB)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Form", "ß", None, QtGui.QApplication.UnicodeUTF8))
        self.sil_to3.setText(QtGui.QApplication.translate("Form", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Form", "(BC)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QtGui.QApplication.translate("Form", "3. Temel Ödev", None, QtGui.QApplication.UnicodeUTF8))
        self.hesapla_to4.setText(QtGui.QApplication.translate("Form", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("Form", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("Form", "(ABC)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("Form", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.sil_to4.setText(QtGui.QApplication.translate("Form", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("Form", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("Form", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QtGui.QApplication.translate("Form", "4. Temel Ödev", None, QtGui.QApplication.UnicodeUTF8))
        self.maprenderer.setTabText(self.maprenderer.indexOf(self.tab), QtGui.QApplication.translate("Form", "Temel Ödevler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "X2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "Y2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "YP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "XP", None, QtGui.QApplication.UnicodeUTF8))
        self.hesapla_2.setText(QtGui.QApplication.translate("Form", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.temizle_2.setText(QtGui.QApplication.translate("Form", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.maprenderer.setTabText(self.maprenderer.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Önden Kestirme", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "X2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Y2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "X3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Y3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "YP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "XP", None, QtGui.QApplication.UnicodeUTF8))
        self.c.setText(QtGui.QApplication.translate("Form", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.hesapla.setText(QtGui.QApplication.translate("Form", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.maprenderer.setTabText(self.maprenderer.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Geriden Kestirme", None, QtGui.QApplication.UnicodeUTF8))
        self.hesaplak.setText(QtGui.QApplication.translate("Form", "Hesapla", None, QtGui.QApplication.UnicodeUTF8))
        self.temizlek.setText(QtGui.QApplication.translate("Form", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "___________________________________________________________", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "BS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.maprenderer.setTabText(self.maprenderer.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Karayolu Hesapları", None, QtGui.QApplication.UnicodeUTF8))
        self.render.setText(QtGui.QApplication.translate("Form", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#00007f;\">* Map Renderer SHP formatındaki haritaların PNG görüntü formatına dönüştürülmesini sağlar. SHP formatındaki verinin görüntü formatına dönüştürülmeden önce dosya ismi &quot;render.shp&quot; olarak değiştirilmelidir.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.maprenderer.setTabText(self.maprenderer.indexOf(self.tab_9), QtGui.QApplication.translate("Form", "Map Renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.raporla.setText(QtGui.QApplication.translate("Form", "Raporla", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#000000;\">* Sınır Koordinat Raporu &quot;SINIR.shp&quot; adlı SHP dosyalarında bulunan vektör verideki kırılma noktalarının koordinat raporu halinde katman katman kaydedilmesini sağlar. Ayrıca SHP dosyasındaki katmanları Polygon ve MultiPoligon olarak olarak sınıflandırır.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.maprenderer.setTabText(self.maprenderer.indexOf(self.tab_10), QtGui.QApplication.translate("Form", "Sınır Koordinat Raporu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#aa0000;\">GeoCalculator 1.0</span></p><p>GeoCalculator, ölçme hesaplamaları, harita görselleştirme ve raporlama programcıklarını sunan bir CBS yazılımdır. Linux, MacOS ve Windows işletim sistemlerinde çalışabilir.</p><p><span style=\" font-weight:600;\">Edip Ahmet TAŞKIN</span></p><p><br/><span style=\" color:#00007f;\">geomath31@gmail.com</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.maprenderer.setTabText(self.maprenderer.indexOf(self.tab_11), QtGui.QApplication.translate("Form", "Hakkında", None, QtGui.QApplication.UnicodeUTF8))

